Repository aurora-is-near/aurora-eth-connector, pull requests merged in 2023-05, with the labels that each got.

#27 chore: increase clippy lints level and tiny refactoring
  Cargo.lock
  README.md
  eth-connector-tests/Cargo.toml
  eth-connector-tests/src/connector.rs
  eth-connector-tests/src/lib.rs
  eth-connector-tests/src/migration.rs
  eth-connector-tests/src/utils.rs
  eth-connector/Cargo.toml
  eth-connector/src/admin_controlled.rs
  eth-connector/src/connector.rs
  eth-connector/src/connector_impl.rs
  eth-connector/src/deposit_event.rs
  eth-connector/src/lib.rs
  eth-connector/src/log_entry.rs
  eth-connector/src/migration.rs
  eth-connector/src/proof.rs
  eth-connector/src/types.rs
Labels: enhancement

#36 Feat: remove doposit-event field
  eth-connector-tests/src/connector.rs
  eth-connector-tests/src/utils.rs
  eth-connector/src/deposit_event.rs
Labels: enhancement

#38 Fix: `engine_storage_deposit` refund
  eth-connector/src/lib.rs
Labels: fix

#28 Feat: use `aurora-workspace` as a testing framework
  Cargo.lock
  eth-connector-tests/Cargo.toml
  eth-connector-tests/src/connector.rs
  eth-connector-tests/src/migration.rs
  eth-connector-tests/src/utils.rs
  eth-connector/Cargo.toml
Labels: do-not-merge, tests, aurora-workspace

#51 Extend `ft_transfer_call` gas check
  eth-connector/src/lib.rs
Labels: enhancement

#54 chore: optimise converting error into message
  Cargo.lock
  eth-connector-tests/Cargo.toml
  eth-connector/src/types.rs
Labels: enhancement

#53 Fix `verify_log_entry` call
  eth-connector/src/connector.rs
  eth-connector/src/connector_impl.rs
  eth-connector/src/lib.rs
  eth-connector/src/proof.rs
Labels: enhancement

#57 chore: some tests refactoring
  .env/development.env
  .env/local.env
  .env/mainnet.env
  .env/testnet.env
  eth-connector-tests/src/connector.rs
  eth-connector-tests/src/migration.rs
  eth-connector-tests/src/utils.rs
Labels: tests
