Repository aurora-is-near/aurora-eth-connector, pull requests merged in 2023-03, with the labels that each got.

#14 Fix (audit AUR-03): signer_id for: `deposit` and `withdraw`
  eth-connector-tests/src/connector.rs
  eth-connector-tests/src/utils.rs
  eth-connector/src/admin_controlled.rs
  eth-connector/src/connector_impl.rs
  eth-connector/src/lib.rs
Labels: audit, fix

#18 Chore: add test for Proof::get_key
  eth-connector/src/proof.rs
Labels: fix

#20 Feat: Register `owner_id` account
  eth-connector/src/lib.rs
Labels: enhancement

#19 chore: add test for checking pause control
  eth-connector/src/admin_controlled.rs
  eth-connector/src/lib.rs
Labels: enhancement

#21 Fix: set FungibleToken::account_storage_usage to 0
  eth-connector/src/lib.rs
Labels: bug
